POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhbm5zIiwiaWQiOiI2OThjNDc1NWIwNWYwMzEwMDk3OWQ5OWEiLCJpYXQiOjE3NzEyNDAxNzEsImV4cCI6MTc3MTI0MTk3MX0.1_ms393qmZDUmlIUy6kaXflXhcA9lGDoJVNYYDMwmmo

{
  "title": "The fast and the furious",
  "author": "Dr.Schnuggels",
  "url": "http://ff.com",
  "likes": 4
}