FROM node:24
WORKDIR /usr/src/app

COPY . .

ARG VITE_BACKEND_URL=http://localhost:8080/api
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}

RUN npm ci

RUN npm run build

RUN npm install -g serve
CMD ["serve", "-n", "dist"]